apiVersion: kubelet.config.k8s.io/v1beta1

authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false

authorization:
  mode: AlwaysAllow

kind: KubeletConfiguration
staticPodPath: /etc/kubernetes/manifests
cgroupDriver: systemd

clusterDNS:
  - "10.1.1.2"
