apiVersion: v1
clusters:
- cluster:
    server: https://10.10.0.10:6443
    insecure-skip-tls-verify: true
    token: 28e01ea7-97be-4a6f-87a5-b9feb5c8d87c
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin
  user:
     token: 28e01ea7-97be-4a6f-87a5-b9feb5c8d87c
